{% set version = "1.3.2" %}

package:
  name: wsproto
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/w/wsproto/wsproto-{{ version }}.tar.gz
  sha256: b86885dcf294e15204919950f666e06ffc6c7c114ca900b060d6e16293528294

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - h11 >=0.16.0,<1.0

test:
  imports:
    - wsproto
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}
about:
  home: https://github.com/python-hyper/wsproto/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Pure Python, pure state-machine WebSocket implementation.
  description: |
    This repository contains a pure-Python implementation of a WebSocket protocol stack.
    It’s written from the ground up to be embeddable in whatever program you choose to use,
    ensuring that you can communicate via WebSockets, as defined in RFC6455, regardless of your programming paradigm.

    This repository does not provide a parsing layer, a network layer, or any rules about concurrency.
    Instead, it’s a purely in-memory solution, defined in terms of data actions and WebSocket frames.
    RFC6455 and Compression Extensions for WebSocket via RFC7692 are fully supported.
  doc_url: https://wsproto.readthedocs.io/en/latest/
  dev_url: https://github.com/python-hyper/wsproto

extra:
  recipe-maintainers:
    - maxyme
    - dhirschfeld
    - ocefpaf
